steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      [
        'gcloud', 'compute', 'firewall-rules', 'create', 'allow-mediasoup-udp',
        '--direction', 'INGRESS',
        '--priority', '1000',
        '--network', 'default',
        '--action', 'ALLOW',
        '--rules', 'udp:10000-10100',
        '--source-ranges', '0.0.0.0/0',
        '--target-tags', 'mediasoup-sfu'
      ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      [
        'gcloud', 'compute', 'firewall-rules', 'create', 'allow-mediasoup-tcp',
        '--direction', 'INGRESS',
        '--priority', '1000',
        '--network', 'default',
        '--action', 'ALLOW',
        '--rules', 'tcp:3016',
        '--source-ranges', '0.0.0.0/0',
        '--target-tags', 'mediasoup-sfu'
      ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      [
        'gcloud', 'compute', 'instances', 'create', 'mediasoup-sfu-instance',
        '--zone', 'asia-south1-b',
        '--machine-type', 'e2-medium',
        '--tags', 'http-server,https-server,mediasoup-sfu',
        '--metadata-from-file', 'startup-script=startup.sh',
        '--boot-disk-size', '20GB'
      ]


timeout: 1800s
options:
  logging: CLOUD_LOGGING_ONLY